Parameters:
  KeyName: 
    Description: The EC2 key Pair
    Type: AWS::EC2::KeyPair::KeyName
  EC2Name:
    Description: EC2 name
    Type: String
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
     SecurityGroups:
      - !Ref InstanceSecurityGroup
     ImageId: ami-0e8d228ad90af673b
      InstanceType: t2.micro
     KeyName: !Ref KeyName
     Tags:
     - Key: Name 
       Value: !Ref EC2Name
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  PublicIp:
    Description: Server public IP
    Value: !GetAtt Ec2Instance.PublicIp
